# Generated by Django 5.0.1 on 2024-04-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/watchlist')),
                ('storyline', models.CharField(blank=True, max_length=500)),
                ('avg_rating', models.FloatField(default=0)),
                ('total_rating', models.IntegerField(default=0)),
                ('length', models.IntegerField()),
                ('premier', models.DateField()),
                ('director', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('stars', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='genre_list', to='watchlist.category')),
            ],
        ),
    ]
