# Generated by Django 5.0.1 on 2024-04-28 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='premier',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='release',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='watchlist.release'),
            preserve_default=False,
        ),
    ]
