# Generated by Django 5.0.1 on 2024-04-28 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_remove_watchlist_premier_watchlist_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='release',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='watchlist.release'),
        ),
    ]
